=== borborisovai/IThubPracticeProjects/ControlPointXML3/notebook.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
    <xs:element name="notebook">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="offices" type="officesType"/>
                <xs:element name="person" type="personType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="officesType">
        <xs:sequence>
            <xs:element name="office" type="officeType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="officeType" mixed="true">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="code" type="xs:ID" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="personType">
        <xs:sequence>
            <xs:element name="name">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="first" type="xs:string"/>
                        <xs:element name="surname" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="address">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="city" type="xs:string"/>
                        <xs:element name="street" type="xs:string"/>
                        <xs:element name="index" type="postalIndexType"/>
                    </xs:all>
                </xs:complexType>
            </xs:element>
            <xs:element name="phones">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="phone" type="phoneType" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="office" type="xs:IDREF" use="required"/>
    </xs:complexType>
    <xs:simpleType name="postalIndexType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{6}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="phoneType">
        <xs:simpleContent>
            <xs:extension base="phoneStringType">
                <xs:attribute name="type" use="optional">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="work"/>
                            <xs:enumeration value="home"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="phoneStringType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{3}-\d{2}-\d{2}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== borborisovai/IThubPracticeProjects/ControlPointXML3/notebook.xml
<?xml version="1.0" encoding="UTF-8"?>
<notebook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="notebook.xsd">

    <offices>
        <office code="A1">Headquarters</office>
        <office code="B2">Regional Office</office>
    </offices>

    <person id="p1" office="A1">
        <name>
            <first>Ivan</first>
            <surname>Petrov</surname>
        </name>
        <address>
            <city>Moscow</city>
            <street>Lenina 10</street>
            <index>123456</index>
        </address>
        <phones>
            <phone type="work">123-45-67</phone>
            <phone type="home">234-56-78</phone>
        </phones>
    </person>

    <person id="p2" office="B2">
        <name>
            <first>Anna</first>
            <surname>Ivanova</surname>
        </name>
        <address>
            <index>654321</index>
            <street>Pushkina 5</street>
            <city>Saint Petersburg</city>
        </address>
        <phones>
            <phone>345-67-89</phone>
        </phones>
    </person>

</notebook>
